### ISSUE TITLE
Failing tests on Ubuntu 16.04 ruby 2.3.1p112

### ISSUE THREAD

**Issue by eelcomaljaars** [github/octocatalog-diff#11]
Three failed tests running on Ubuntu 16.04  amd64 / ruby  2.3.1p112

vagrant@ptester:/vagrant/octocatalog-diff$ rake
1 processes for 108 specs, ~ 108 specs per process
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F.F.....F..........

Failures:

  1) OctocatalogDiff::Util::Parallel with parallel processing should parallelize and return task results
     Failure/Error: expect(one_time).to be_within(2).of(two_time)
       expected 1478169453 to be within 2 of 1478169456
     # ./spec/octocatalog-diff/tests/util/parallel_spec.rb:43:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:112:in `block in run'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:101:in `loop'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:101:in `run'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:30:in `block (2 levels) in setup'

  2) OctocatalogDiff::Util::Parallel with parallel processing should kill running tasks when one task fails
     Failure/Error: expect(one_result.status).to eq(nil)

       expected: nil
            got: true

       (compared using ==)
     # ./spec/octocatalog-diff/tests/util/parallel_spec.rb:100:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:112:in `block in run'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:101:in `loop'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:101:in `run'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:30:in `block (2 levels) in setup'

  3) OctocatalogDiff::Util::Parallel with parallel processing should kill other tasks when a validator method fails
     Failure/Error: expect(result[0].status).to eq(nil)

       expected: nil
            got: true

       (compared using ==)
     # ./spec/octocatalog-diff/tests/util/parallel_spec.rb:237:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:112:in `block in run'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:101:in `loop'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:101:in `run'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.3.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:30:in `block (2 levels) in setup'

Finished in 4 minutes 30.6 seconds (files took 1.59 seconds to load)
1097 examples, 3 failures

Failed examples:

rspec ./spec/octocatalog-diff/tests/util/parallel_spec.rb:8 # OctocatalogDiff::Util::Parallel with parallel processing should parallelize and return task results
rspec ./spec/octocatalog-diff/tests/util/parallel_spec.rb:79 # OctocatalogDiff::Util::Parallel with parallel processing should kill running tasks when one task fails
rspec ./spec/octocatalog-diff/tests/util/parallel_spec.rb:213 # OctocatalogDiff::Util::Parallel with parallel processing should kill other tasks when a validator method fails

1097 examples, 3 failures

Took 272 seconds (4:32)

**Comment by kpaulisse** [comment]
Hey @eelcomaljaars !

Thanks for the note. The problem you are observing here is due to these particular tests being based on the time an action takes to complete, to determine whether a process was killed or ran to completion. In this particular case it appears that the tests took longer on your machine than they should have, resulting in processes actually exiting rather than being killed. I'll look into eliminating the time-based nature of these tests to make them more robust. However I can say that you can almost certainly ignore these failures.
