### ISSUE TITLE
Question on changed Error Type for missing Puppet binary

### ISSUE THREAD

**Issue by mschuchard** [github/octocatalog-diff#120]
Recently in 1.2.0, the Error Type returned from the API for passing a nonexistent Puppet binary to octocatalog-diff changed from `OctocatalogDiff::Errors::CatalogError` to `Errno::ENOENT`. I wanted to confirm this is expected/desired. Thanks!

**Comment by kpaulisse** [comment]
Yes. This was a fix to separate out errors in your configuration (e.g. not pointing at the correct puppet binary) from errors with your catalog itself. I consider the previous implementation to be a bug that has been corrected.

`OctocatalogDiff::Errors::CatalogError` should only be raised if there is an actual problem with the catalog.

Thanks!

**Comment by mschuchard** [comment]
Thanks for the prompt info. Makes sense to me.
