### ISSUE TITLE
Keyword error in example .octocatalog-diff.cfg.rb

### ISSUE THREAD

**Issue by eelcomaljaars** [github/octocatalog-diff#13]
The documentation at https://github.com/github/octocatalog-diff/blob/master/doc/configuration.md (and the sample config file) have the settings[:hiera_yaml_file] keyword documented, while the commandline options is --hiera-config. 

When I used the key settings[:hiera_config] in my config instead  things seem to work out better.

**Comment by kpaulisse** [comment]
Thanks for the report @eelcomaljaars ! You are indeed correct. I have put in a PR to fix the documentation and example configuration file, and this issue will automatically close when it's been merged!
