### ISSUE TITLE
Question: ca cert to use with PuppetDB fact retrieval

### ISSUE THREAD

**Issue by mschuchard** [github/octocatalog-diff#137]
There are two different suggested ca certs for retrieving facts from the PuppetDB -

`/etc/puppetlabs/puppet/ssl/certs/ca.pem`: https://github.com/github/octocatalog-diff/blob/master/examples/octocatalog-diff.cfg.rb#L97
`/etc/puppetlabs/puppetdb/ssl/ca.pem`: https://github.com/github/octocatalog-diff/blob/master/doc/configuration-puppetdb.md#supplying-necessary-information-via-configuration-files

I was wondering which is the recommended cert to use. I was googling around to see what people were doing for this, but it appears everyone is using fact files instead of going this route.

**Comment by kpaulisse** [comment]
This really has to do with your own setup and I'm not sure we can publish a guideline or best practice here. In my setup the puppetdb certificate is generated via the same CA as puppet, so I can use `/etc/puppetlabs/puppet/ssl/certs/ca.pem` and it works great. If someone's puppetdb certificate came from a different CA, then they'd have to point to that.

I'll make the documentation consistent to use `/etc/puppetlabs/puppet/ssl/certs/ca.pem`.

**Comment by mschuchard** [comment]
Got it. I figured this had something with how a split install master would be architected.
Thanks!
