### ISSUE TITLE
Command line param fact-file does not override config-file parameter fact_file

### ISSUE THREAD

**Issue by vinzent** [github/octocatalog-diff#139]
> Description of problem

- What did you do?

I configured `fact_file` setting in git repos .octocatalog-diff.cfg.rb and tried to override the config-file setting with the cli param `--fact-file`.

- What happened?

the config-file setting value was used instead of the setting provided by the command line.

- What did you expect to happen?

the command line parameter value should take precedence over the config-file value (like for `--from` or `--to`)

- How can someone reproduce the problem?

add the `fact_file` setting to the config-file and try to override  command line

> Command used and debugging output

`octocatalog-diff --hostname=el6 --fact-file=spec/octocatalog-diff/facts/el6.yaml`

> Platform and version information

- Your OS: EL7
- Your Ruby version: 2.0.0p648
- Your version of Puppet: 4.10.4
- Your version of octocatalog-diff: 1.3.0

**Comment by vinzent** [comment]
thanks @kpaulisse !

**Comment by kpaulisse** [comment]
Of course! 😺

Thanks for the report.
