### ISSUE TITLE
Ability to use pe-token for puppetdb fact retrieval

### ISSUE THREAD

**Issue by TraGicCode** [github/octocatalog-diff#156]
I belive this is not possible but it would be nice to be able to retrieve puppetdb facts via a passed in pe-token instead of having to generate certs signed by the puppet ca for every developer.

**Comment by kpaulisse** [comment]
Seems that [the API supports this](https://puppet.com/docs/puppetdb/5.1/api/query/curl.html#using-an-rbac-token-pe-only), so it's something we could look to add. I'll tag this as a potential enhancement.

**Comment by kpaulisse** [comment]
Implemented in version 1.5.2.

You can wait for that to be released, or try it earlier via https://github.com/github/octocatalog-diff/pull/172.
