### ISSUE TITLE
catalog diff fails with invalid UTF-8

### ISSUE THREAD

**Issue by tuxmea** [github/octocatalog-diff#182]
> Description of problem

- What did you do?

run octocatalog-diff with --fact-file on a control-repository.
we use hiera and pe as enc
we use puppetdb for old catalogs and storeconfigs
we have prepared environments (production and feature branch) of control repository

Note: we query facts from PuppetDB and merge them with server_facts

- What happened?

Error message:

> /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/filter/compilation_dir.rb:52:in `filtered?': invalid byte sequence in UTF-8 (ArgumentError)
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/filter.rb:62:in `block in filter'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/filter.rb:62:in `reject!'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/filter.rb:62:in `filter'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/filter.rb:42:in `block in apply_filters'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/filter.rb:42:in `each'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/filter.rb:42:in `apply_filters'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:204:in `catdiff'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:80:in `diff'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/cli/diffs.rb:34:in `diffs'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/api/v1/catalog-diff.rb:54:in `catalog_diff'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/api/v1.rb:19:in `catalog_diff'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/cli.rb:119:in `cli'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/octocatalog-diff-1.5.2/bin/octocatalog-diff:34:in `<top (required)>'
	from /opt/puppetlabs/puppet/bin/octocatalog-diff:23:in `load'
	from /opt/puppetlabs/puppet/bin/octocatalog-diff:23:in `<main>'

- What did you expect to happen?

We expected to see the diff report

- How can someone reproduce the problem?

Unsure.
Run octocatalog/diff on a control/repository

> Command used and debugging output
/opt/puppetlabs/puppet/bin/octocatalog-diff \
  -n $node \
  -f production \
  -t HPC2052 \
  --debug \
  --fact-file ~/node.json

> Platform and version information

- Your OS: RHEL 7
- Your Ruby version:  ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux] (Bundled with PE 2017.2)
- Your version of Puppet: 4.10.5 - PE 2017.2
- Your version of octocatalog-diff:  octocatalog-diff 1.5.2

**Comment by tuxmea** [comment]
solved by setting locale to en_US
`export LANG=en_US` 
`export LC_ALL=en_US`

**Comment by usev6** [comment]
Just for the record (and maybe it helps someone else in the future): I've run into a similiar problem. octocatalog-diff was dying with an internal error ```Error: Failed to compile catalog for node foo.example.com: "\xC2" on US-ASCII``` when processing a ```.erb``` template containing an unicode character.

This didn't happen when using puppet 4.10.12 (installed as a gem), but the error occured with puppet 5.5.17 (again installed as a gem).

I had ```LANG``` and ```LC_ALL``` set to ```en_US.UTF-8``` and exported, but I had to add ```LANG``` to the list of passed environment variables in ```~/.octocatalog-diff.cfg.rb```:
```
174c174
<       settings[:pass_env_vars] = %w(HOME PATH GEM_PATH)
---
>       settings[:pass_env_vars] = %w(HOME PATH GEM_PATH LANG)
```

**Comment by elfchief** [comment]
> and maybe it helps someone else in the future

Just thought I'd note, as an encouragement, that this did indeed help someone else today (that'd be me) and probably saved me hours of troubleshooting (at minimum!). So rather than just silently taking the fix and running with it, just thought I'd note explicitly that I really appreciate you taking a few minutes to share back your solution on this.

**Comment by gabostefanovic** [comment]
O

**Comment by mookie-** [comment]
> [...] and maybe it helps someone else in the future [...]

Someone from the future wants to thank you! :bow:
