### ISSUE TITLE
Consider not using LCS by default or allow switching it off

### ISSUE THREAD

**Issue by nbarrientos** [github/octocatalog-diff#207]
Hi,

[Hashdiff](https://github.com/github/octocatalog-diff/blob/master/lib/octocatalog-diff/catalog-diff/differ.rb#L525) uses [LCS by default](https://github.com/liufengyun/hashdiff#use_lcs) when comparing arrays. This algorithm produces a friendlier and easier to read diff for humans, but at [high cost](https://github.com/liufengyun/hashdiff/issues/49) O(n<sup>2</sup>).

Would you consider a patch to either disable LCS or perhaps to allow switching it off via the command line? I'd happy to prepare it.

Thanks.

**Comment by ahayworth** [comment]
@nbarrientos Yes, I think an option to toggle LCS (on by default) would be reasonable. I'll be happy to review such a PR! :smile:
