### ISSUE TITLE
please review PRs

### ISSUE THREAD

**Issue by isaiahfrantz** [github/octocatalog-diff#213]
Any idea what the time line is to get PRs merged?
There are 3 waiting, including mine. The oldest is from December 2017 and none of them have comments from the maintainers.
Please take a look, it would be nice to be able to use the mainline again instead of pulling a fork.

**Comment by isaiahfrantz** [comment]
Anybody else get the feeling that we should start a permanent fork? This project is starting to feel a bit abandoned since Kevin Paulisse left GitHub :(

**Comment by BarnumD** [comment]
Yes, i'm getting that feeling. :( Is there a fork yet?

**Comment by alexjfisher** [comment]
@kpaulisse Hope you are well.  Would you be able to prod any of your former colleagues?

[Vox Pupuli](https://voxpupuli.org/) might be able to help maintain a fork, but we usually consider hard forks as a last resort.
Many thanks,
Alex

**Comment by ahayworth** [comment]
Hi friends -

Apologize for the delays. We're going to take a look at open PRs and issues today. 

❤️ ❤️ ❤️ ❤️

**Comment by ahayworth** [comment]
Everything looks more or less okay, and I'm testing things internally at GitHub! :heart:

**Comment by ahayworth** [comment]
Behold, 1.6.0: https://github.com/github/octocatalog-diff/releases/tag/1.6.0
and at rubygems: https://rubygems.org/gems/octocatalog-diff/versions/1.6.0

Thanks again for your patience - we're going to do better maintaining this. :heart:
