### ISSUE TITLE
Feature request: PuppetDB 2.3 v3 API support

### ISSUE THREAD

**Issue by bentlema** [github/octocatalog-diff#22]
> Description of problem

- What did you do?
Installed and configured octocatalog-diff for our Puppet Enterprise 3.8.6 infra which runs PuppetDB 2.3.8
- What happened?
Getting error "not found in PuppetDB (404 - Not Found)"
- What did you expect to happen?
Expected the node to be found
- How can someone reproduce the problem?
Attempt to use octocatalog-diff with an older PE release without a fully-implemented v4 API (such as PE 3.8.x)

> Command used and debugging output

[root@puppol10 code]# /opt/octocatalog-diff/bin/octocatalog-diff -n puptst04.mgmt -f mbentle8_future -t mbentle8 --debug
D, [2016-11-10T13:04:25.712273 #20246] DEBUG -- : Running octocatalog-diff 0.5.4 with ruby 2.0.0
D, [2016-11-10T13:04:25.712350 #20246] DEBUG -- : Command line arguments: ["-n", "puptst04.mgmt", "-f", "mbentle8_future", "-t", "mbentle8", "--debug"]
D, [2016-11-10T13:04:25.712387 #20246] DEBUG -- : Running on host puppol10 (x86_64-linux)
D, [2016-11-10T13:04:25.712529 #20246] DEBUG -- : Initialized OctocatalogDiff::Catalog::Computed for from-catalog
D, [2016-11-10T13:04:25.712567 #20246] DEBUG -- : Initialized OctocatalogDiff::Catalog::Computed for to-catalog
D, [2016-11-10T13:04:25.712611 #20246] DEBUG -- : Initialized parallel task result array: size=2
D, [2016-11-10T13:04:25.714334 #20248] DEBUG -- : Begin build_catalog for mbentle8_future
D, [2016-11-10T13:04:25.714510 #20248] DEBUG -- : Setting up Puppet catalog build for mbentle8_future
D, [2016-11-10T13:04:25.714571 #20248] DEBUG -- : Catalog for mbentle8_future will be built with OctocatalogDiff::Catalog::Computed
D, [2016-11-10T13:04:25.714624 #20248] DEBUG -- : Calling build for object OctocatalogDiff::Catalog::Computed
D, [2016-11-10T13:04:25.714711 #20248] DEBUG -- : Start retrieving facts for puptst04.mgmt from OctocatalogDiff::Catalog::Computed
D, [2016-11-10T13:04:25.714837 #20248] DEBUG -- : Retrieving facts from PuppetDB
D, [2016-11-10T13:04:25.715348 #20251] DEBUG -- : Begin build_catalog for mbentle8
D, [2016-11-10T13:04:25.715506 #20251] DEBUG -- : Setting up Puppet catalog build for mbentle8
D, [2016-11-10T13:04:25.715565 #20251] DEBUG -- : Catalog for mbentle8 will be built with OctocatalogDiff::Catalog::Computed
D, [2016-11-10T13:04:25.715618 #20251] DEBUG -- : Calling build for object OctocatalogDiff::Catalog::Computed
D, [2016-11-10T13:04:25.715777 #20251] DEBUG -- : Start retrieving facts for puptst04.mgmt from OctocatalogDiff::Catalog::Computed
D, [2016-11-10T13:04:25.715835 #20251] DEBUG -- : Retrieving facts from PuppetDB
D, [2016-11-10T13:04:25.726546 #20251] DEBUG -- : Failed build_catalog for mbentle8: OctocatalogDiff::Facts::FactRetrievalError Node puptst04.mgmt not found in PuppetDB (404 - Not Found)
W, [2016-11-10T13:04:25.740494 #20246]  WARN -- : Catalog compile for mbentle8_future was aborted due to another failure
/opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:209:in `add_parallel_result': Catalog for 'to' (mbentle8) failed to compile with OctocatalogDiff::Facts::FactRetrievalError: Node puptst04.mgmt not found in PuppetDB (404 - Not Found) (OctocatalogDiff::CatalogDiff::Cli::Catalogs::CatalogError)
   /opt/octocatalog-diff/lib/octocatalog-diff/facts/puppetdb.rb:55:in `fact_retriever'
   /opt/octocatalog-diff/lib/octocatalog-diff/facts.rb:28:in `initialize'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog-util/facts.rb:48:in `new'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog-util/facts.rb:48:in `facts_from_puppetdb'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog-util/facts.rb:81:in `compute_facts'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog-util/facts.rb:25:in `facts'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog/computed.rb:59:in `build'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog.rb:60:in `build'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:221:in `build_catalog'
   /opt/octocatalog-diff/lib/octocatalog-diff/util/parallel.rb:26:in `call'
   /opt/octocatalog-diff/lib/octocatalog-diff/util/parallel.rb:26:in `execute'
   /opt/octocatalog-diff/lib/octocatalog-diff/util/parallel.rb:114:in `block in run_tasks_parallel'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:451:in `call'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:451:in `call_with_index'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:422:in `process_incoming_jobs'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:404:in `block in worker'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:395:in `fork'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:395:in `worker'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:386:in `block in create_workers'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:385:in `each'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:385:in `each_with_index'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:385:in `create_workers'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:327:in `work_in_processes'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:241:in `map'
   /usr/local/share/gems/gems/parallel-1.9.0/lib/parallel.rb:203:in `each'
   /opt/octocatalog-diff/lib/octocatalog-diff/util/parallel.rb:90:in `run_tasks_parallel'
   /opt/octocatalog-diff/lib/octocatalog-diff/util/parallel.rb:72:in `run_tasks'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:98:in `build_catalog_parallelizer'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:32:in `catalogs'
   /opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli.rb:107:in `cli'
   /opt/octocatalog-diff/bin/octocatalog-diff:74:in `<main>'
	from /opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:118:in `block in build_catalog_parallelizer'
	from /opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:112:in `each'
	from /opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:112:in `build_catalog_parallelizer'
	from /opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:32:in `catalogs'
	from /opt/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli.rb:107:in `cli'
	from /opt/octocatalog-diff/bin/octocatalog-diff:74:in `<main>'

> Platform and version information

- Your OS:  RHEL7.1 / Linux 3.10.0-327.28.3.el7.x86_64
- Your Ruby version: 2.0.0p598 (2014-11-13) [x86_64-linux]
- Your version of Puppet: 3.8.7 (Puppet Enterprise 3.8.6)
- Your version of octocatalog-diff: 0.5.4

> Do the tests pass from a clean checkout?

Yes, all rake tests pass.

> Anything else to add that you think will be helpful?

There are a number of places where the v4 API calls are used, but these do not appear to be supported in PuppetDB 2.3:

```
./octocatalog-diff/catalog/puppetdb.rb:        uri = "/pdb/query/v4/catalogs/#{@node}"
./octocatalog-diff/facts/puppetdb.rb.orig:        uri = "/pdb/query/v4/nodes/#{node}/facts"
./octocatalog-diff/facts/puppetdb.rb:        uri = "/pdb/query/v4/nodes/#{node}/facts"
```

The v3 API seems to support equivalent calls:

https://docs.puppet.com/puppetdb/2.3/api/query/v3/nodes.html
https://docs.puppet.com/puppetdb/2.3/api/query/v3/catalogs.html

> Feature Request

Could a flag such as --use-puppetdb-api-v3 be added so that we can use octocatalog-diff and PE 3.8.6 / PuppetDB 2.3?

**Comment by kpaulisse** [comment]
We have some old code in our Puppet repo from when we were on an earlier version of PuppetDB. I won't have an actual environment against which to test that change though but I'll see what I can do. Thanks.

**Comment by bentlema** [comment]
I've tested this with PuppetDB v2.3.8 (comes with Puppet Enterprise 3.8.6), and it does work now.  Thanks for implementing this!  Much appreciated.

I did have to work around an issue with determining the puppetversion, as it didn't seem to like the PE versioning string like "3.8.7 (Puppet Enterprise 3.8.6)"
