### ISSUE TITLE
Provide new release 2.1.1 or alike?

### ISSUE THREAD

**Issue by mika** [github/octocatalog-diff#262]
octocatalog-diff v2.1.0 got released on 2021-02-18 and since then a few commits piled up, including https://github.com/github/octocatalog-diff/commit/fb924b8b494a3dfd1211bf783414d3c01d93a696 which would be nice to have available for usage with more recent puppet(db) versions.

Thanks for considering! :)

**Comment by MasterMind2k** [comment]
Is this project still alive? Is there an alternative?
