### ISSUE TITLE
Debug failing bootstrap script

### ISSUE THREAD

**Issue by jaxxstorm** [github/octocatalog-diff#4]
> Unable to debug a failing boostrap script
- Added a bootstrap script which runs r10k to boostrap the env
- Nothing, the script should take ~10s to run, but it seems to fail or not complete, and I have no debug output
- If the script exits with something other than exit code 0, we should at least stop
- Add a bootstrap script with something that doesn't exit cleanly

> Command used and debugging output

```
octocatalog-diff -d -n <hostname> --fact-file octocatalog/fact_files/<hostname>.yaml --puppet-binary /usr/local/bin/puppet --fact-override role=base --bootstrap-script octocatalog/script/r10k.sh
```

> Platform and version information
- Your OS: Linux (CentOS 7)
- Your Ruby version: 2.1.5
- Your version of Puppet: 3.8.7
- Your version of octocatalog-diff: 0.5.1

> Do the tests pass from a clean checkout?

yes

> Anything else to add that you think will be helpful?

I'm simply trying to boostrap my environment. My initial bootstrap script was this:

```
bundle install
r10k puppetfile install --verbose --moduledir ../../modules --puppetfile ./Puppetfile
```

This constantly fails to run:

```
D, [2016-10-23T09:32:26.346267 #50548] DEBUG -- : Success: copied /Users/Lee/git/puppet/octocatalog/script/r10k.sh to /var/folders/pm/vtw9fkxn50x63lq7fxzyy9wr0000gn/T/d20161023-50548-hh9gng/octocatalog/script/r10k.sh
D, [2016-10-23T09:32:26.346364 #50548] DEBUG -- : Begin bootstrap with 'octocatalog/script/r10k.sh' in /var/folders/pm/vtw9fkxn50x63lq7fxzyy9wr0000gn/T/d20161023-50548-hh9gng
```

I tried adding all manner of debug options to the script, but it always seems to continue regardless. I then added a bunch of nonsense commands to the bootstrap script and it will continue regardless.

**Comment by kpaulisse** [comment]
Hey @jaxxstorm thanks for the report!

I started a branch over in https://github.com/github/octocatalog-diff/pull/5 to help you figure this out. You're correct that there isn't debugging for a successful bootstrap script (defined as, exit code = 0). In the referenced PR, I have added a `--debug-bootstrap` command line option that will print the output from that script (if any) in the debugging.

Here are a few other tips to help you debug this:

0. If you are running this without specifying a `-t <branch>` in your current development directory, it's assuming you've already bootstrapped your current development directory. In the aforementioned PR I have also added a `--bootstrap-current` option, which will force the bootstrap script to run even in this situation.

0. The bootstrap script runs with a limited set of environment variables being passed. These are defined here: [PWD, HOME, PATH, BASEDIR](https://github.com/github/octocatalog-diff/blob/master/lib/octocatalog-diff/bootstrap.rb#L30-L34). If you need additional variables passed through, you can use for example: `--bootstrap-environment RBENV_VERSION=2.1.5 --bootstrap-environment SECRET_TOKEN=abcdefghijk`. The reason for this design decision is to avoid cross-contamination of environment variables between octocatalog-diff and anything else that may be using ruby.

Please give it a shot with the branch in that PR and see if that gets you any further.

You might also set your bootstrap script to run like so to get even more debugging details:

```
#!/bin/bash -x

bundle install
r10k puppetfile install --verbose --moduledir ../../modules --puppetfile ./Puppetfile
```

**Comment by kpaulisse** [comment]
Fixed (I think) by https://github.com/github/octocatalog-diff/pull/5
