### ISSUE TITLE
octocatalog diff always return no diff between master and branch for all nodes

### ISSUE THREAD

**Issue by dinukxx** [github/octocatalog-diff#76]
First of all Thank you very much for making this opensource and it really has great potential on becoming a central piece of developer CI environment. Documentation is excellent, if we can have couple of more examples on how to use it with a sample repo, it would be simply brilliant . 

I am not sure this is the best place to ask this clarification, please feel free to point me in right direction on clarifications about the octocatalog-diff.  I am a newbie for puppet and octocatalog-diff, kindly pardon any misunderstandings.

Problem :
I am trying to use octocatalog-diff to verify couple of nodes through puppet master (connected via puppetdb) . Every time i do a octocatalog diff  it returns  the catalogs has no difference.  i have tried compiling via facts , still the output is same.
in my local sandbox set up, i have a master and working branch. local working branch clearly have difference changes which master lacks. but using the octocatalog-diff  on master and working branch outputs the same output as no catalog difference 

what my compile catalog looks like : 

`[root@dev local-puppet-sandbox]# octocatalog-diff -n sandbox.test.com --catalog-only -- no-parallel -d
{"tags":["settings","default","node"],"name":"sandbox.test.com","version":"catalogscript","code_id":null,"catalog_uuid":"07e0e0c8-1f27-49ce-973e-a8c46065c247","catalog_format":1,"environment":"production","resources":[{"type":"Stage","title":"main","tags":["stage"],"exported":false,"parameters":{"name":"main"}},{"type":"Class","title":"Settings","tags":["class","settings"],"exported":false},{"type":"Class","title":"main","tags":["class"],"exported":false,"parameters":{"name":"main"}},{"type":"Node","title":"default","tags":["node","default","class"],"exported":false}],"edges":[{"source":"Stage[main]","target":"Class[Settings]"},{"source":"Stage[main]","target":"Class[main]"},{"source":"Class[main]","target":"Node[default]"}],"classes":["settings","default"]}
`

I have tried several different nodes , its the same behavior. what could be the issue ?
any pointers / hints would be greatly appreciated. I can upload my testing repo if that helps too. 

> Platform and version information

- Your OS: centos 7
- Your Ruby version: ruby 2.0.0p648
- Your version of Puppet: PE
- Your version of octocatalog-diff:   octocatalog-diff 0.6.1

> Do the tests pass from a clean checkout?
YES.

**Comment by kpaulisse** [comment]
Your catalog doesn't really look like it has much of anything in it, beyond just the basic stuff. I don't see any file resources or anything else. Are you possibly missing a [hiera configuration](https://github.com/github/octocatalog-diff/blob/master/doc/configuration-hiera.md) or [ENC configuration](https://github.com/github/octocatalog-diff/blob/master/doc/configuration-enc.md) that is needed to classify your nodes and actually bring in the classes?

**Comment by dinukxx** [comment]
Glad to receive a fast response from you.  Unfortunately i have tried with hiera configuration its still the same  and we dont use any external ENC.

hiera output : 

```
[root@dev local-puppet-sandbox]# octocatalog-diff -n centosclient.test.com  --hiera-config hiera.yaml

I, [2017-01-23T15:27:10.829981 #21598]  INFO -- : Catalogs compiled for centosclient.test.com
I, [2017-01-23T15:27:10.832828 #21598]  INFO -- : Diffs computed for centosclient.test.com
I, [2017-01-23T15:27:10.832962 #21598]  INFO -- : No differences
```


I have tried compiling a none existing node , which fails via puppetdb so seems like puppetdb is configured fine.

to give you more visibility i have uploaded my test repo at :  https://github.com/dinukxx/Octocatalogdiff-sandbox

it has two branches (master and workingbranch) where master is behind workingbranch. but catalog compilation doesn't pick that up.  

My puppet master is sitting on master and compiles , pushes changes to the nodes fine. if you do a manual compilation on puppet master , i can clearly see the classes and resources in the catalog.
but using octocatalog-diff , i cant see any of them. [must be missing something]


Branch diff :

```
[root@dev local-puppet-sandbox]# octocatalog-diff -n centosclient.test.com  --hiera-config hiera.yaml -f workingbranch -t master
I, [2017-01-23T15:43:29.884111 #22203]  INFO -- : Catalogs compiled for centosclient.test.com
I, [2017-01-23T15:43:29.884974 #22203]  INFO -- : Diffs computed for centosclient.test.com
I, [2017-01-23T15:43:29.885019 #22203]  INFO -- : No differences
```

 
Any directions would be highly appreciated.

**Comment by dinukxx** [comment]
Any hits or suggestions on what am doing wrong ?

**Comment by jamesandrews-iopp** [comment]
I have exactly the same problem

But I have figured out why

I am not using the production branch and octocatalog-diff does not like this.  Worse, I also use r10k to set up the branches on the server.

I have been too busy with other urgent issues to figure out how to square this circle but it is not impossible, see the documentation on the "preserve environment" flag

**Comment by kpaulisse** [comment]
@dinukxx I looked at your repo and I don't see that your `site.pp` is actually doing anything. If you added `include fileStore` to it, it would probably then try to pull in that class which contains some resources?

**Comment by kpaulisse** [comment]
Closing old issue. If you need additional assistance please feel free to reopen.
