### ISSUE TITLE
OctocatalogDiff::Errors::ConfigurationFileContentError not rasied when expected

### ISSUE THREAD

**Issue by mschuchard** [github/octocatalog-diff#87]
> Description of problem

I am doing an API call like:

```ruby
OctocatalogDiff::API::V1.config(filename: 'metadata.json')
```

where `metadata.json` is a typical Puppet `metadata.json`. I am doing this through a RSpec test to ensure that `OctocatalogDiff::Errors::ConfigurationFileContentError` is raised for a completely bogus Octocatalog-diff configuration file. I double-checked the source code here and feel confident it should fail the first check on content here: https://github.com/github/octocatalog-diff/blob/master/lib/octocatalog-diff/api/v1/config.rb#L86

> Command used and debugging output

RSpec output:

```
expected OctocatalogDiff::Errors::ConfigurationFileContentError with "Configuration must define OctocatalogDiff::Config!" but nothing was raised
```

> Platform and version information

- Your Ruby version: 2.3.1p112
- Your version of octocatalog-diff: 1.0.1

**Comment by kpaulisse** [comment]
Is it possible that your rspec test suite is doing other things that would cause an OctocatalogDiff::Config class to be loaded elsewhere? Do you get consistent results if you just run only the rspec test in question and not your entire suite (e.g. `rspec spec/SOME/PATH/some_file_spec.rb:123`)?

The "load" statement you pointed out is indeed trying to load the file you provided, but the subsequent test for the existence of the class does not necessarily require that the class was defined in the file you loaded.

**Comment by mschuchard** [comment]
If I load a generic text file instead of the metadata file, then the method fails here (throws a standard Ruby SyntaxError since it is a generic text file): https://github.com/github/octocatalog-diff/blob/master/lib/octocatalog-diff/api/v1/config.rb#L82. It was when that occurred that I became suspicious.

However, your theory is correct:

> Is it possible that your rspec test suite is doing other things that would cause an OctocatalogDiff::Config class to be loaded elsewhere?

Once I cleared out the `.config` method from an earlier correct octocatalog-diff config, the test passed exactly as expected. So I see now I incorrectly thought I was instantiating a new `config` method object each time.

So Ruby parse test would fail a successive config file load, but an octocatalog-diff parse would not. Makes sense, and this was good to learn so that I know to only load in one config per execution even with multiple test matrices.

Thanks!
