### ISSUE TITLE
Enable use of git submodules

### ISSUE THREAD

**Issue by zipkid** [github/octocatalog-diff#88]
We use git submodules for our puppet modules.
The following change together with passing -f and -t without leading 'origin/' makes it work.

This would obviously need cli params to enable git submodules and some clean code :-)

lib/octocatalog-diff/catalog-util/git.rb
```
      def self.create_git_checkout_script(branch, path)
        tmp_script = Tempfile.new(['git-checkout', '.sh'])
        tmp_script.write "#!/bin/bash\n"
        tmp_script.write "set -euf -o pipefail\n"
        # tmp_script.write "git archive --format=tar #{Shellwords.escape(branch)} | \\\n"
        # tmp_script.write "  ( cd #{Shellwords.escape(path)} && tar -xf - )\n"
        tmp_script.write "git clone --single-branch -b #{Shellwords.escape(branch)} . #{Shellwords.escape(path)} \n"
        tmp_script.write "( cd #{Shellwords.escape(path)} && git submodule init && git submodule sync  && git submodule update )\n"
        tmp_script.close
        FileUtils.chmod 0o755, tmp_script.path
        at_exit { FileUtils.rm_f tmp_script.path if File.exist?(tmp_script.path) }
        tmp_script.path
      end
```

**Comment by mschuchard** [comment]
FYI this is a major edge case since standard use is librarian-puppet, r10k, or code manager for this.

**Comment by zipkid** [comment]
Thank you, i am very aware of that. Nonetheless, the change/addition to make this 'edge case work' is minor.

**Comment by kpaulisse** [comment]
I think the best implementation here would be to template https://github.com/github/octocatalog-diff/blob/master/lib/octocatalog-diff/catalog-util/git.rb#L52-L62 into an ERB or a static file that uses environment variables, so it's easier to update the underlying script without having it being written out line-by-line.

I'm not at all opposed to supporting submodules here, but I won't really have a way to test it myself on a substantially large code base, since we use librarian internally at GitHub.

**Comment by kpaulisse** [comment]
@zipkid please advise if you're interested in writing this code. If not I will probably have some time next week to make a preliminary attempt at it.

**Comment by zipkid** [comment]
I am not sure i know how to write that.
We can certainly test it. We have, up to now 77 submodules in our puppet control repo.

**Comment by kpaulisse** [comment]
Marked as in progress - I've started a branch to address this (and refactor a bit around how external scripts are run in general).
