### ISSUE TITLE
Two questions on node parameter

### ISSUE THREAD

**Issue by mschuchard** [github/octocatalog-diff#89]
1. As far as I can tell from the provided template in this repo, the node parameter cannot be set in the octocatalog-diff config file, and therefore must be passed via the API (or CLI with normal use).

2. As far as I can tell, the API is expecting a single node parameter per execution. If I wanted to do multiple nodes per execution and gather results for each I would need to do something like https://github.com/github/octocatalog-diff/blob/master/examples/ci/puppet_catalogs_spec.rb#L39 where sequential executions are performed. As it is, I am guessing that if one execution compiled catalogs for, say, ten nodes, and nine succeeded and one failed, then octocatalog-diff would return a failure overall. This is actually fine for me given how people and companies use puppet-check, especially its preponderance in CI. I was just hoping for a confirmation.

Thanks!

**Comment by kpaulisse** [comment]
1. Regarding setting the node in the configuration file - it's possible. Just define `settings[:node]` in the configuration. Generally speaking any command line option can be set via the configuration file. Note that the command line always takes precedence over the configuration file.

    The node isn't in any of the example configuration files because at GitHub our configuration file is checked in to our puppet repository, and provides sane defaults for 99% of the use cases. If you're using the configuration file as an oft-changing (or perhaps even transient) way to configure a particular run, it's possible to use the configuration file and no command line arguments at all. (Have a look in https://github.com/github/octocatalog-diff/tree/master/lib/octocatalog-diff/cli/options, and set the variables exactly like the method that handles your favorite command line option is doing.)

2. That is correct, one API call = catalog or catalog-diff for one node. At this point I don't envision building any handling of multiple nodes into octocatalog-diff, because everyone will probably want to do different things.

    The CI template is a simplified version of what we use at GitHub (and we perform tens of thousands of catalog-diffs per day in our development cycles). The advantage to using a separate `describe` for each node is that this can be parallelized. We use the [test queue](https://github.com/tmm1/test-queue) gem to parallelize the catalog compilations (and in some cases, to distribute the compilations across multiple nodes). I suspect this strategy would also work with `parallel_tests` or any similar approaches to run multiple specs in parallel.

    Our general rule is that if a system has N cores, we allow N `catalog-only` or N/2 `catalog-diff` to run at the same time (since a `catalog-diff` is compiling 2 catalogs, old and new, at the same time).

**Comment by mschuchard** [comment]
1. Thanks for the clarification. I interpreted the example config as a template for all possible options and not an optimized "sane defaults" config.

2. So I guess I should be more specific here. Say I am doing:

```ruby
nodes.each { |node| OctocatalogDiff::API::V1.catalog(node: node) }
```

If there is at least one failure, then this would return a failure overall in the sense that a `OctocatalogDiff::Errors::CatalogError` would be thrown on the first failed catalog, correct?

**Comment by kpaulisse** [comment]
> If there is at least one failure, then this would return a failure overall

Yes, since any failing catalog would raise an error, the sample code you provided would exit with an error status as soon as it came across a bad catalog.

I'm sure you realize that your code as written would execute the checks serially, and you could consider parallelizing that execution to take advantage of multiple CPU cores (since each catalog compile basically pegs 1 core).

**Comment by mschuchard** [comment]
Yeah, this is all kind of "code design/architect" at this point and I am trying to figure out the optimal path forward before "code engineering".

I guess I have one final question about this. Say I did (still iteratively):

```ruby
nodes.each do |node|
  begin
    OctocatalogDiff::API::V1.catalog(node: node)
  rescue OctocatalogDiff::Errors::CatalogError
    puts "#{node} had a catalog compilation error"
  end
end
```

If I had nodes 1..5 and node 3 had catalog compilation error, would this output:

`node 3 had a catalog compilation error`

or

```
node 3 had a catalog compilation error
node 4 had a catalog compilation error
node 5 had a catalog compilation error
```

**Comment by kpaulisse** [comment]
My guess would be it would output `node 3 had a catalog compilation error` but never raise an exception. You'd be handling the error by printing a message but not doing anything else particularly interesting with it.

**Comment by mschuchard** [comment]
Thanks for all the helpful info; ready to move forward again.
