### ISSUE TITLE
--ignore-tags has an unspecified behavior

### ISSUE THREAD

**Issue by jairojunior** [github/octocatalog-diff#97]
The docs state that: 

`--ignore-tags STRING1[,STRING2[,...]] Specify tags to ignore`

But if you set this option to anything it will cause tags to be completely left out of a diff: https://github.com/github/octocatalog-diff/blob/master/lib/octocatalog-diff/catalog-diff/differ.rb#L271

Is this the case to change docs or to split it in two args/options?

**Comment by kpaulisse** [comment]
Thanks for pointing this out. The lines you cited date back to a pre-release time when there was an explicit option to ignore tags (which was renamed to `--include-tags` in subsequent versions). I've made the fix in https://github.com/github/octocatalog-diff/pull/105.
